---
jupyter:
  jupytext:
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.10.3
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Data, types, strings

Here we explore types of things, and converting between them.

```{python}
# Run this cell to set up the notebook, but please don't change it.
# These lines load the tests.
from client.api.notebook import Notebook
ok = Notebook('data_types.ok')
```

This is an integer (counting number):

```{python}
# Run this cell
a = 10
```

Use `type` to confirm that this is a value of `int` type:

```{python}
# Your code here.  It should use type to display the type of the value in "a"
#<- ...
type(a)
```

```{python}
_ = ok.grade('q_type_int')
```

This is a floating point number.

```{python}
b = 1.1
```

Use `type` to confirm that this is a value of `float` type:

```{python}
# Your code here.  It should use type to display the type of the value in "b"
#<- ...
type(b)
```

```{python}
_ = ok.grade('q_type_float')
```

This is a string:

```{python}
c = "some text"
```

Use `type` to confirm that this is a value of `str` type:

```{python}
# Your code here.  It should use type to display the type of the value in "c"
#<- ...
type(c)
```

```{python}
_ = ok.grade('q_type_string')
```

Show what you get when you use the 'float' function to convert the value in `a` into a float.

```{python}
# Convert "a" into a float, show the result.
#<- ...
float(a)
```

What happens if you use `int` to convert `b` to an integer?

```{python}
# Convert "b" into an integer, show the result
#<- ...
int(b)
```

What happens if you use `str` to convert `b` to an string?

```{python}
# Convert "b" into an string, show the result
#<- ...
str(b)
```

What happens if you use `float` to convert `c` into a floating point value?

```{python tags=c("raises-exception")}
# Convert "c" into a floating point value
#<- ...
float(c)
```

Now, if you have time - make new code cells below and try the following
operations.  To make a new cell, go to the "Insert" item on the menu, and
choose "Insert Cell Below" (or "Above").

Try these operations in a new cell each.   What do you see?

* `a + b`
* `a + c`
* `b + c`

Now try converting `a`, `b`, `c` to Boolean (True / False) values with the
`bool` function.

Try converting a Boolean value to `int`, `float` and `str`.
