---
jupyter:
  jupytext:
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.10.3
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Strings and variables


Strings are Python's way of storing bits of text.

Variables have names, and it can be confusing when you are looking at a name,
or a string.

This notebook is to practice the distinction between the two.

```{python}
# Run this cell to set up the notebook, but please don't change it.
# These lines load the tests.
from client.api.notebook import Notebook
ok = Notebook('strings_vars.ok')
```

Who isn't a Marvel fan? (that's rhetorical - if you aren't, please, just grin
and bear it).


In the next cell, make a variable with name `title` that has the value
`"Captain "`.  Notice that `"Captain "` is a string, and `title` is a variable
name.  Notice too that the string has a space at the end.

```{python}
#<- title = ...
title = "Captain "
#<->
# Show the variable contents
title
```

```{python}
_ = ok.grade('q_captain')
```

Now make another string with name `person`, and value `"Marvel"`.

```{python}
#<- person = ...
person = "Marvel"
#<->
# Show the value
person
```

```{python}
_ = ok.grade('q_marvel')
```

Now use `title` and `person` to make a new variable `character`, that has the
value `"Captain Marvel"`:

```{python}
#<- character = ...
character = title + person
#<->
# Display the result
character
```

```{python}
_ = ok.grade('q_capt_marvel')
```

Here I'm trying to make a new variable `another_character` by appending the
string `"America"` to the value of `title`, but there's a mistake.  Fix the
mistake.

```{python}
#<- another_character = title + America
another_character = title + "America"
#<->
# Display the result
another_character
```

```{python}
_ = ok.grade('q_capt_america')
```

Here I'm trying to make a new variable `third_character` by appending the
string `"Carter"` to the string `"Peggy "`, to get the value `"Peggy Carter"`,
but there are some mistakes.  Fix the mistakes.

```{python}
#<- "third_character" = Peggy + Carter
third_character = 'Peggy ' + 'Carter'
#<->
# Display the result
third_character
```

```{python}
_ = ok.grade('q_peggy_carter')
```

In an [alternative
universe](https://en.wikipedia.org/wiki/Alternative_versions_of_Captain_America#Civil_War),
our own Captain America has become General America.  Use string methods to
substitute "General" for "Captain" in `another_character`:

```{python}
#- Edit the line below to do the substitution.
#<- alternative_character = another_character...
alternative_character = another_character.replace('Captain', 'General')
#<->
# Display the result
alternative_character
```

```{python}
_ = ok.grade('q_gen_america')
```

## Liking people who like foreigners

As everybody now knows, the word for someone who does not like foreigners is
[xenophobe](https://en.wikipedia.org/wiki/Xenophobia). It comes from Greek,
where "xenos" means a stranger or foreigner and "phobos" is fear.

Similarly, if you like foreigners, you can be a
[xenophile](https://en.wikipedia.org/wiki/Xenophilia), where "philia" in Greek
means love or attraction.

Or you could be afraid of people who are afraid of foreigners.  Then you would
be a "xenophobophobe".  Or you could like people who like foreigners, and be a
"xenophilophile".

Because "xenophobophobe" is such a useful word, we will put it in its own
variable:

```{python}
fears_who_fears = "xenophobophobe"
```

Use your `replace` skills to turn "xenophobophobe" to "xenophilophile".  For
this question, and the ones below, try and find the smallest bit of text that
you can replace.

```{python}
#<- likes_who_likes = fears_who_fears...
likes_who_likes = fears_who_fears.replace('ob', 'il')
#<->
likes_who_likes
```

But you might have a darker side.  Perhaps you like people who dislike
foreigners.  That would be a "xenophobophile".   Make that word, using
`replace`.

```{python}
#<- likes_who_dislikes = fears_who_fears....
likes_who_dislikes = fears_who_fears.replace('obe', 'ile')
#<->
likes_who_dislikes
```

Use replace on `likes_who_dislikes` above to get "xenophilophobe" - someone who
is afraid of people who like strangers.

```{python}
#<- dislikes_who_likes = likes_who_dislikes...
dislikes_who_likes = likes_who_dislikes.replace('obo', 'ilo').replace('ile', 'obe')
#<->
dislikes_who_likes
```

## Last check

```{python}
# For your convenience, you can run this cell to run all the tests at once.
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```
